# Site settings
title: "redbyzan"
description: redbyzan's blog theme MAD4Jekyll
logo: favicon.png
discus_shortname: RogerJo
header-img: img/home-bg.jpg
email: jmirs83@gmail.com
url: http://redbyzan.github.io
search: true
share: true
comments:
    provider : disqus
    disqus :
      short_name : redbyzan.github.io

# Read Time is a calculator tp provide post read-time based on word count. Usage is recommended.
readtime: true

# Specify the average Words per minute. If not defined, 180 will be used
wpm: 200

# Owner/author information
owner:
  name:   redbyzan
  avatar: me.jpeg
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    redbyzan's blog theme MAD4Jekyll

# Social networking links used in footer. Update and remove as you like.
twitter_username: jmirs6
facebook_username: jovvpd
github_username: redbyzan
#deviantart_username: MAD4Jekyll
#500px_username: MAD4Jekyll
#flickr_username: MAD4Jekyll
#instagram_username: MAD4Jekyll

 
# Internal nav
nav:
 writing: "source_url/writing/"
 gallery: "source_url/gallery/"
 about: "source_url/about/"


# Server
destination:      	 ./_site
port:             	 4000

# Build settings
highlighter:         rouge
markdown:           redcarpet
redcarpet:
    extensions:     
     - Hard_wrap
     - no_intra_emphasis
     - strikethrough
     - fenced_code_blocks
     - autolink
     - tables
     - with_toc_data
     - highlight
     - footnotes
    input:          GFM
sass:
    style:          :compressed


 # PAGINATION
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/writing/page:num/"
permalink: "/writing/:title/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
slugify: "pretty"

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-67144579-2
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
